// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4w72MMlJVE-4P_Hw3rQFBALP0ydpDRZE',
    appId: '1:779836204660:web:fe648177bcc396d7211321',
    messagingSenderId: '779836204660',
    projectId: 'chat-app-93146',
    authDomain: 'chat-app-93146.firebaseapp.com',
    storageBucket: 'chat-app-93146.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbNA_k44FrHUlZYczip-opSRpUKi91D8',
    appId: '1:779836204660:android:00a69e1abb3b62ed211321',
    messagingSenderId: '779836204660',
    projectId: 'chat-app-93146',
    storageBucket: 'chat-app-93146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdh1CWn9ydAvoo8q2fyuz8TlgtSdb0A4s',
    appId: '1:779836204660:ios:27b324b70383b61c211321',
    messagingSenderId: '779836204660',
    projectId: 'chat-app-93146',
    storageBucket: 'chat-app-93146.appspot.com',
    iosClientId: '779836204660-5msp9csv8gtiaupd0k4mpmub5llrsh18.apps.googleusercontent.com',
    iosBundleId: 'com.example.mChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdh1CWn9ydAvoo8q2fyuz8TlgtSdb0A4s',
    appId: '1:779836204660:ios:27b324b70383b61c211321',
    messagingSenderId: '779836204660',
    projectId: 'chat-app-93146',
    storageBucket: 'chat-app-93146.appspot.com',
    iosClientId: '779836204660-5msp9csv8gtiaupd0k4mpmub5llrsh18.apps.googleusercontent.com',
    iosBundleId: 'com.example.mChat',
  );
}
